modules:
  - seacliff

input:
  calexp:
    file_name: "tests/data/cexp.fits.fz"

gal:
  type: Exponential
  half_light_radius: 0.5
  flux: 1e5

psf:
  type : Gaussian
  fwhm: 0.8

image:
  type: Single
  wcs:
    type: RubinSkyWCS
    wcs: "$(@input.calexp).getWcs()"

  noise:
    type: RubinNoise
    calexp: "$(@input.calexp)"

  size: 53

output:
  file_name: image_with_rubin_noise.fits
