name: tests

on:
  push:
    branches:
      - main
  pull_request: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
        with:
          condarc: |
            channels:
              - conda-forge
            show_channel_urls: true
            channel_priority: strict
          environment-file: environment.yml
          environment-name: seacliff

      - name: install code
        run: |
          python -m pip install --no-deps --no-build-isolation -e .

      - name: run tests
        run: |
          pytest -n 2 -vv --cov=seacliff --cov-report=term-missing --cov-report=xml tests

      - name: upload coverage
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v.5.52
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
