name: tests

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: install dev tools and code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          python -m pip install -e .
          mamba install -y -q \
            flake8 \
            pytest \
            pytest-xdist \
            pytest-cov \
            black

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 seacliff
          black --check seacliff

      - name: install rubin science pipelines
        shell: bash -l {0}
        run: |
          mamba install \
            --file=requirements.txt

      - name: run tests
        shell: bash -l {0}
        run: |
          pytest -n 2 -vv --cov=seacliff --cov-report term-missing seacliff

      - name: upload coverage
        uses: codecov/codecov-action@v2
