name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          condarc: |
            channels:
              - conda-forge
            show_channel_urls: true
            channel_priority: strict
          environment-file: environment.yml
          environment-name: seacliff

      - name: install code
        run: |
          python -m pip install --no-deps --no-build-isolation -e .

      - name: run tests
        run: |
          pytest -n 2 -vv --cov=seacliff --cov-report=term-missing --cov-report=xml tests

      - name: upload coverage
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v.5.52
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
