name: tests

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.11"
          channels: conda-forge
          channel-priority: strict
          show-channel-urls: true

      - name: install dev tools and code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          python -m pip install --no-deps --no-build-isolation -e .
          conda install -y -q \
            pytest \
            pytest-xdist \
            pytest-cov \
            ruff

      - name: lint
        shell: bash -l {0}
        run: |
          ruff check seacliff
          ruff format seacliff

      - name: lint tests
        shell: bash -l {0}
        run: |
          ruff check tests
          ruff format tests

      - name: install rubin science pipelines
        shell: bash -l {0}
        run: |
          conda install \
            --file=requirements.txt

      - name: run tests
        shell: bash -l {0}
        run: |
          pytest -n 2 -vv --cov=seacliff --cov-report=term-missing --cov-report=xml tests

      - name: upload coverage
        uses: codecov/codecov-action@v2
